name: Deploy Automatico su Rosina

on:
  push:
    branches:
      - main  # Si attiva solo quando pushi sul ramo principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connessione SSH e Pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: rosina.cs.unibo.it
          username: lorenzo.ricci27
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/web/site252630/html/
            git pull origin main
            rm -rf .github  # <--- Questo cancella la cartella su Rosina dopo ogni aggiornamento